---
# tasks file for K8SSlave
- name: "Installing Docker and IP route-tc"
  package:
    name:
      - docker
      - iproute-tc

- name: "Configuring yum repo for Kubernetes"
  yum_repository:
    name: kubernetes
    description: "YUM repository for Kubernetes"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: "Installing kubeadm"
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: "Starting docker service"
  service:
    name: docker
    state: started
    enabled: yes
  
- name: "Starting kubelet service"
  service:
    name: kubelet
    state: started
    enabled: yes

- name: "Creating daemon.json"
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "exec-opts": ["native.cgroupdriver=systemd"]
      }
  register: output
  ignore_errors: yes

- name: "Restarting docker on change"
  service:
    name: docker
    state: restarted
  when: output.changed == true

- name: "Enable bridge routing"
  shell: 'echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables'

- name: "Copying k8s.conf file"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
